# Generated by Django 3.2.14 on 2023-07-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='onCampus',
            field=models.BooleanField(default=False),
        ),
    ]
