# Generated by Django 4.2.3 on 2023-07-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('Library', 'Library'), ('Gate', 'Gate'), ('Admin', 'Admin')], default='Admin', max_length=10),
        ),
    ]
